import { MachineProcedure } from "./types";

// Node names below are 100% verified — this GLB was generated by
// scripts/build_placeholder_tensile_tester.py in this same codebase, so
// there's no ambiguity about what exists. The MACHINE ITSELF is still a
// schematic placeholder (see lib/machines.ts statusNote), so treat the
// physical arrangement as illustrative — but the highlighting and the
// crosshead_descend animation genuinely work against this asset, unlike the
// robotic manipulator / hydraulic press files where the underlying geometry
// has no nameable parts at all.
//
// tbt-04 (set test parameters) is this project's SECOND worked example of
// real parameter-validated error detection (the first is the milling
// machine's spindle speed). I checked ASTM E8/E8M crosshead-speed guidance
// against several independent secondary sources before hardcoding a number,
// because they didn't all agree with each other — some quoted 0.015 mm/mm/min
// as a pre-yield limit, others gave slightly different figures depending on
// which of E8's three control methods (stress rate / strain rate / crosshead
// speed) they were describing. The value used below (Method C, crosshead
// speed, pre-yield: strain rate <= 0.015 mm/mm of gauge length per minute)
// was the one most consistently corroborated. Verify it against the actual
// ASTM E8/E8M standard text (not a secondary source) before using this for
// real student evaluation — and note this only checks the PRE-YIELD limit;
// E8 permits a faster rate after yield, which this simplified check doesn't
// model.

export const tensileBendingTesterProcedure: MachineProcedure = {
  machineSlug: "tensile-bending-tester",
  title: "Tensile / Bending Test Machine — Specimen Test Cycle (placeholder model)",
  steps: [
    {
      id: "tbt-01",
      order: 1,
      title: "Inspect frame and grips",
      instruction:
        "Check the frame, columns, and grips for damage or obstruction before mounting a specimen.",
      acceptedActions: ["inspect_frame"],
      safetyCritical: true,
      highlightNodes: ["column_left", "column_right", "base_plate"],
    },
    {
      id: "tbt-02",
      order: 2,
      title: "Zero (tare) the load cell",
      instruction:
        "Tare the load cell with no specimen loaded so readings start from zero.",
      acceptedActions: ["tare_load_cell"],
      commonErrors: {
        mount_specimen: "Tare the load cell before mounting the specimen, or your reading will be offset by whatever preload exists.",
      },
      highlightNodes: ["load_cell"],
    },
    {
      id: "tbt-03",
      order: 3,
      title: "Mount the specimen",
      instruction: "Secure the specimen in the upper and lower grips, aligned with the load axis.",
      acceptedActions: ["mount_specimen"],
      safetyCritical: true,
      commonErrors: {
        start_test: "You can't start the test with no specimen mounted — the crosshead would just drive into the grips.",
      },
      highlightNodes: ["upper_grip", "lower_grip"],
    },
    {
      id: "tbt-04",
      order: 4,
      title: "Set test parameters",
      instruction:
        "Enter the specimen gauge length and the crosshead speed you'd set. This is checked against ASTM E8/E8M's pre-yield strain-rate limit (Method C, crosshead speed control), not just accepted as clicked.",
      acceptedActions: ["set_test_parameters"],
      paramInputs: [
        { key: "gaugeLengthMm", label: "Gauge length", unit: "mm" },
        { key: "crossheadSpeedMmMin", label: "Crosshead speed", unit: "mm/min" },
      ],
      evaluate: (params) => {
        const { gaugeLengthMm, crossheadSpeedMmMin } = params;
        if (!gaugeLengthMm || gaugeLengthMm <= 0) {
          return { result: "incorrect", message: "Gauge length must be a positive number." };
        }
        if (!crossheadSpeedMmMin || crossheadSpeedMmMin <= 0) {
          return { result: "incorrect", message: "Crosshead speed must be a positive number." };
        }
        // Strain rate = crosshead speed / gauge length, in mm/mm/min.
        const strainRate = crossheadSpeedMmMin / gaugeLengthMm;
        // ASTM E8/E8M, Method C (crosshead speed), pre-yield limit — see the
        // file-level comment above for sourcing and its caveats.
        const MAX_STRAIN_RATE = 0.015;
        if (strainRate > MAX_STRAIN_RATE) {
          return {
            result: "incorrect",
            message: `That's a strain rate of ${strainRate.toFixed(4)} mm/mm/min — exceeds the ASTM E8 pre-yield crosshead-speed limit of ${MAX_STRAIN_RATE} mm/mm/min for a ${gaugeLengthMm}mm gauge length. Reduce crosshead speed to ${(MAX_STRAIN_RATE * gaugeLengthMm).toFixed(2)} mm/min or below, or the yield point measurement won't be standard-compliant.`,
          };
        }
        return {
          result: "correct",
          message: `Strain rate = ${strainRate.toFixed(4)} mm/mm/min — within the ASTM E8 pre-yield crosshead-speed limit. Good selection.`,
        };
      },
      highlightNodes: ["control_panel", "control_panel_screen"],
    },
    {
      id: "tbt-05",
      order: 5,
      title: "Clear the area and start the test",
      instruction:
        "Confirm no one's hands are near the grips, then start the test. The crosshead will travel under stepper-motor/lead-screw drive.",
      acceptedActions: ["start_test"],
      safetyCritical: true,
      highlightNodes: ["crosshead", "lead_screw", "stepper_motor"],
      animationClip: "crosshead_descend",
    },
    {
      id: "tbt-06",
      order: 6,
      title: "Monitor load–displacement reading",
      instruction:
        "Watch the load cell reading on the controller screen until the specimen yields or fractures.",
      acceptedActions: ["monitor_test"],
      highlightNodes: ["load_cell", "control_panel_screen"],
    },
    {
      id: "tbt-07",
      order: 7,
      title: "Return crosshead and remove specimen",
      instruction:
        "Return the crosshead to its start position, then remove the tested specimen from the grips.",
      acceptedActions: ["reset_and_remove"],
      highlightNodes: ["crosshead", "upper_grip"],
    },
  ],
};
