import { MachineProcedure } from "./types";

export const verticalMillingMachineProcedure: MachineProcedure = {
  machineSlug: "vertical-milling-machine",
  title: "Vertical Milling Machine — Workholding & First Cut",
  steps: [
    { id: "vmm-01", order: 1, title: "Inspect the machine and clear the table", instruction: "Check the spindle, table, vice and surrounding area. Remove loose objects before setup.", acceptedActions: ["inspect_machine"], safetyCritical: true },
    { id: "vmm-02", order: 2, title: "Mount the workpiece in the vice", instruction: "Open the vice, seat the selected workpiece against the fixed jaw, then tighten the moving jaw with the handle.", acceptedActions: ["secure_workpiece"], safetyCritical: true },
    { id: "vmm-03", order: 3, title: "Mount and secure the end mill", instruction: "Install the cutter in the tool holder and confirm it is secure before bringing it near the workpiece.", acceptedActions: ["mount_tool"], safetyCritical: true },
    { id: "vmm-04", order: 4, title: "Set spindle speed", instruction: "Enter cutter diameter and RPM. The simulator checks cutting speed Vc = πDN/1000 for the educational HSS/mild-steel example.", acceptedActions: ["set_spindle_speed"], paramInputs: [{ key: "diameterMm", label: "Cutter diameter", unit: "mm" }, { key: "rpm", label: "Spindle speed", unit: "RPM" }], evaluate: (params) => { const d=params.diameterMm, rpm=params.rpm; if(!(d>0) || !(rpm>0)) return {result:"incorrect",message:"Cutter diameter and spindle speed must both be positive."}; const vc=Math.PI*d*rpm/1000; if(vc<20) return {result:"incorrect",message:`Cutting speed is ${vc.toFixed(1)} m/min, below the 20 m/min educational target range. Increase RPM or cutter diameter.`}; if(vc>35) return {result:"safety_violation",message:`Cutting speed is ${vc.toFixed(1)} m/min, above the 35 m/min educational upper limit for this example. Reduce RPM.`}; return {result:"correct",message:`Cutting speed = ${vc.toFixed(1)} m/min. The selected speed is inside the 20–35 m/min educational range.`}; } },
    { id: "vmm-05", order: 5, title: "Start the spindle", instruction: "Start the spindle and observe stable tool rotation before advancing toward the workpiece.", acceptedActions: ["start_spindle"] },
    { id: "vmm-06", order: 6, title: "Set depth of cut and feed", instruction: "Set a shallow first-pass depth and feed rate appropriate to the selected workpiece and cutter.", acceptedActions: ["set_feed_depth"], paramInputs: [{ key: "feed", label: "Feed", unit: "mm/rev" }, { key: "depth", label: "Depth of cut", unit: "mm" }], evaluate: (params) => { const f=params.feed, d=params.depth; if (!(f > 0) || !(d > 0)) return { result: "incorrect", message: "Feed and depth must both be positive." }; if (f > 0.8 || d > 2.5) return { result: "safety_violation", message: "The selected first-pass settings are too aggressive for this educational setup. Reduce feed to 0.8 mm/rev or less and depth to 2.5 mm or less." }; if (f > 0.5 || d > 1.5) return { result: "incorrect", message: "Use a shallower first pass. Try feed ≤ 0.5 mm/rev and depth ≤ 1.5 mm for the training cut." }; return { result: "correct", message: `Feed ${f.toFixed(2)} mm/rev and depth ${d.toFixed(1)} mm are suitable for the first educational pass.` }; } },
    { id: "vmm-07", order: 7, title: "Engage table feed and cut the workpiece", instruction: "Engage feed. The table moves under the rotating cutter and the simulated workpiece shows the first machined pass.", acceptedActions: ["engage_feed"] },
    { id: "vmm-08", order: 8, title: "Retract, stop and release the workpiece", instruction: "Retract the cutter, stop the spindle and loosen the vice handle before removing the finished part.", acceptedActions: ["retract_and_release"] },
  ],
};
